runtime: python39
entrypoint: python main.py

handlers:
  # 处理静态文件（CSS、JS等）
  - url: /static
    static_dir: static

  # 处理图片文件
  - url: /image
    static_dir: image

  # 根路径和其他所有路径由 Python 脚本处理
  - url: /.*
    script: auto
